#!/bin/sh
# Generate rekeyvacuum.c from SQLite3 amalgamation and print it to stdout.

if [ "$#" -ne 1 ] || ! [ "$1" = "-" -o -f "$1" ]; then
  echo "Usage: $0 <SQLITE3_AMALGAMATION>" >&2
  echo " e.g.: $0 sqlite3.c" >&2
  exit 1
fi

die() {
    echo "[-]" "$@" >&2
    exit 2
}

VERSION="$(sed -n 's/^#define SQLITE_VERSION[^"]*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)"$/\1/p' sqlite3.h)"
[ -z "$VERSION" ] && die "Cannot find SQLite3 version"

cat <<EOF
/*
** 2018-02-24
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
************************************************************************
**
** This file contains an adjusted version of function sqlite3RunVacuum
** to allow reducing or removing reserved page space.
** For this purpose the number of reserved bytes per page for the target
** database is passed as an extra parameter to the adjusted function.
**
** NOTE: When upgrading to a new version of SQLite3 it is strongly
** recommended to check the original function sqlite3RunVacuum of the
** new version for relevant changes, and to incorporate them in the
** adjusted function below.
**
** Change 0: Rename function to sqlite3RunVacuumForRekey()
** Change 1: Add parameter 'int nRes'
** Change 2: Remove local variable 'int nRes'
** Change 3: Remove initialization 'nRes = sqlite3BtreeGetOptimalReserve(pMain)'
**
** This code is generated by the script rekeyvacuum.sh from SQLite version $VERSION.
*/
EOF
sed -n '/^SQLITE_PRIVATE int sqlite3RunVacuum([^;]*$/,/^}$/p' "$1" \
    | sed 's/sqlite3RunVacuum/sqlite3RunVacuumForRekey/' \
    | sed 's/^\([^ )][^)]*\)\?){$/\1, int nRes){/' \
    | grep -v "int nRes;\|nRes = " \
    | grep "^" || die "Error generating rekeyvacuum.c"
